### ISSUE TITLE
getting error while running node app.js (already configured environment variable)

### ISSUE THREAD

**Issue by honeyonsys** [twilio/starter-node#3]
F:\laragon\www\twillio_starter\node_modules\twilio\lib\RestClient.js:35
            throw 'RestClient requires an Account SID and Auth Token set explicitly ' +
            ^
RestClient requires an Account SID and Auth Token set explicitly or via the TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN environment variables

**Comment by shubhamsethoctro** [comment]
enter your twilio auth key and sid from your Twilio account console
